MailManager.Web/Controllers/EmailAccountController.cs
using MailManager.Service.IService;
using MailManager.Web.Extension;
using MailManager.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MailManager.Web.Controllers
{
    public class EmailAccountController : Controller
    {
        // GET: EmailAccount
        private readonly IEmailAccountService _service;
        public EmailAccountController(IEmailAccountService service)
        {
            _service = service;
        }
        public ActionResult Index()
        {
            var model = new List<EmailAccountVM>();
            try
            {
                model = _service.GetAll().Select(item=>item.ToModel()).ToList();
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
            return View(model);
        }

        public ActionResult Edit(int Id)
        {
            var model = new EmailAccountVM();
            try
            {
                if(Id==0)
                {
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
                }
                var entity = _service.GetById(Id);
                
                if(entity == null)
                {
                    return HttpNotFound();
                }
                model = entity.ToModel();   
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EmailAccountVM model)
        {
            try
            {
                var entity = model.ToEntity();
                _service.Update(entity);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
            return View(model);
        }
    }
}

MailManager.Web/Views/EmailAccount/Edit.cshtml
@model MailManager.Web.ViewModel.EmailAccountVM

@{
    ViewData["Title"] = "Edit";

    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h5 style="margin-bottom:25px;">Edit Mail Configuration</h5>



@using (Html.BeginForm("Edit", "EmailAccount", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">

        <div class="col-md-4">
            <div class="form-group">

                @Html.LabelFor(model => model.DisplayName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">

                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">

                @Html.LabelFor(model => model.Host, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Host, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Host, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <div class="row">

        <div class="col-md-4">
            <div class="form-group">

                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-2">
            <div class="form-group">

                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-1">
            <div class="form-group">

                @Html.LabelFor(model => model.Port, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Port, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Port, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-1">
            <div class="form-group">

                @Html.LabelFor(model => model.EnableSsl, htmlAttributes: new { @class = "control-label" })
                @Html.CheckBoxFor(model => model.EnableSsl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnableSsl, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-1">
            <div class="form-group">

                @Html.LabelFor(model => model.UseDefaultCredentials, htmlAttributes: new { @class = "control-label" })
                @Html.CheckBoxFor(model => model.UseDefaultCredentials, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UseDefaultCredentials, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>


    <div class="form-group">
        @Html.ActionLink("Back to Home", "Index", "Home", null, new { @class = "btn btn-danger" })
        <input type="submit" value="Save" class="btn btn-dark" />
    </div>




</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
}

MailManager.Web/Views/EmailAccount/Index.cshtml
@model IEnumerable<MailManager.Web.ViewModel.EmailAccountVM>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<center><h3 style=" margin-bottom: 5px; color: dodgerblue; margin-bottom:25px" ><strong> Mail Configuration <i class="fas fa-cog"> </i></strong></h3></center>
<table table id="itemTable" class="table table-bordered table-striped table-sm">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DisplayName)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Port)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EnableSsl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UseDefaultCredentials)
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DisplayName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td>
                    <span class="password-mask"> **************** </span>
                    <span class="password-hidden" style="display: none;">@item.Password</span>
                    <a href="#" class="toggle-password">
                        <i class="fas fa-eye text-primary"></i>
                    </a>
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Port)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.EnableSsl)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UseDefaultCredentials)
                </td>


                <td>

                    <a href="@Url.Action("Edit", new { item.Id })" class="fas fa-pencil-alt text-info">

                    </a>


                </td>

            </tr>
        }
    </tbody>
</table>

<div class="d-flex gap-2">
    
    <a href="/Home/Index" class="btn btn-danger w-20">Back to Home</a>
</div>

<script>

   $(document).ready(function () {
        $(".toggle-password").click(function (e) {
            e.preventDefault();
            var parentTd = $(this).closest("td");
            var masked = parentTd.find(".password-mask");
            var actual = parentTd.find(".password-hidden");

            if (masked.is(":visible")) {
                masked.hide();
                actual.show();
                $(this).find("i").removeClass("fa-eye").addClass("fa-eye-slash");
            } else {
                masked.show();
                actual.hide();
                $(this).find("i").removeClass("fa-eye-slash").addClass("fa-eye");
            }
        });
    });</script>